### ISSUE TITLE
Terraform Provider Development Program - Initial Review

### ISSUE THREAD

**Issue by cgriggs01** [ucloud/terraform-provider-ucloud-old#2]
Hi Team,

My name is Chris, I'm a member of the Partner team @ HashiCorp.

I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. The review was done on the master branch at git commit `8ce7f72`. 

- [x] There are two tests that have consistently failed when running the make target `testacc`, the first appears to be a timeout error and possiblt an unauthoized update error. I've included the test output for both these tests. We will need to make sure all tests are passing. 

```
=== RUN   TestAccUCloudLBRule_basic
--- FAIL: TestAccUCloudLBRule_basic (129.64s)
    testing.go:527: Step 0 error: Error applying: 1 error occurred:
        	* ucloud_lb_attachment.foo: 1 error occurred:
        	* ucloud_lb_attachment.foo: error in create lb attachment, cannot send request, Get https://api.ucloud.cn?Action=AllocateBackend&Port=80&ProjectId=org-xotkcf&PublicKey=XXXXXX%3D%3D&Region=cn-sh2&ResourceId=uhost-jror1a&ResourceType=UHost&ULBId=ulb-sai42l&VServerId=vserver-yoyhcd&Signature=XXXXXX: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
```

```
=== RUN   TestAccUCloudSubnet_basic
--- FAIL: TestAccUCloudSubnet_basic (13.72s)
    testing.go:527: Step 1 error: Error applying: 1 error occurred:
        	* ucloud_subnet.foo: 1 error occurred:
        	* ucloud_subnet.foo: do UpdateSubnetAttribute failed in update subnet subnet-orfnk5, api:
        [server.RetCodeError] 291 Action [UpdateSubnetAttribute], Type [DEFAULT] unauthorized error
```

- [x] Make sure you have an open source license in the repository, preferably a [MPL2](https://github.com/hashicorp/terraform/blob/master/LICENSE) which is what we use across all our terraform providers.

**Comment by yufeiminds** [comment]
Hi, @cgriggs01 

Thanks for your feedback, we are trying to reproduce and fix them.

- [x] **Case1**. For network error, it will retried on next release.
- [x] **Case2**. Your account is denied for subnet. we will enable it. 
- [x] **License**. It will be added on next release.

**Comment by tangjunjie119** [comment]
Hi Chris @cgriggs01, 

As an add on to what is mentioned by yufei, 

- the retry logic will be added in the following release, in case a timeout error occurred; 
- Your account has been granted with proper permissions already, it is now an authorized account;
- Thanks for the reminder, the required license will be inserted in the following release.

**Comment by cgriggs01** [comment]
Hey Team, 

Thanks for making those update, I am just hitting more error consistently:
```
--- FAIL: TestAccUCloudLBAttachment_basic (77.87s)
    testing.go:527: Step 0 error: Error applying: 1 error occurred:
        	* ucloud_lb.foo: 1 error occurred:
        	* ucloud_lb.foo: wait for lb initialize failed in create lb ulb-rgxjqw, cannot send request, Get https://api.ucloud.cn?Action=DescribeULB&ProjectId=org-xotkcf&PublicKey=Ulj20CSmsgsNohTfDtmttYxmE3h7T10K5mcfFQPGKi2vmf06puU9tw%3D%3D&Region=cn-sh2&ULBId=ulb-rgxjqw&Signature=7d83efb13f1643930214738b569b8d8b2fe46189: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
``` 

Looks like another "Timeout Error", you might want to add some additional retry logic here.

**Comment by littlecole** [comment]
hi,everybody,bless U

**Comment by tangjunjie119** [comment]
Hi Chris@cgriggs01, 

Thanks for pointing out this error which we believed it's basically due to the global network latency, the team is now working on resolution and hopefully it will be optimized in following release. We will keep you updated.

Jason

**Comment by cgriggs01** [comment]
@tangjunjie119 

Thank you! yes, let me know and we can then move forward with the program review.

Best,
Chris

**Comment by tangjunjie119** [comment]
Hi Chris @cgriggs01 ,

Sorry for keep your waiting , we've made some adjustments and few rounds of tests on reducing the global network latency during the past two weeks, Now you should be able to re-test the provider as the enhancement is already in place.

Kindly let us know if further error occurred, 

We are ready to obtain your green light to move ahead. :)

Jason 

Thanks & Regards,

**Comment by cgriggs01** [comment]
Team, 

Everything looks great for my initial review, I'm going to close this issue and another one will be opened by the reviewing engineer from the Terraform Ecosystem Team with their feedback. 

I expect them to post the feedback by next week. I'll also be speaking with you in the #tpdp-ucloud Slack channel.

**Comment by tangjunjie119** [comment]
Thanks very much Chris, 

Please let us know once we added in the Slack, we haven't received the invitation yet.

Jason

**Comment by cgriggs01** [comment]
Jason - I spoke with our IT team, and they there was a hangup but you should receive the email invitations today. 

Let me know if you do not get them.

Best,
Chris
